"""create followups table

Revision ID: 12e77ae3b86a
Revises: dea444a279a2
Create Date: 2026-09-13 00:49:32.924722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12e77ae3b86a'
down_revision: Union[str, Sequence[str], None] = 'dea444a279a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interaction_id', sa.Integer(), nullable=False),
    sa.Column('assigned_to', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['interaction_id'], ['interactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_followups_assigned_to'), 'followups', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_followups_interaction_id'), 'followups', ['interaction_id'], unique=False)
    op.create_index(op.f('ix_followups_status'), 'followups', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_followups_status'), table_name='followups')
    op.drop_index(op.f('ix_followups_interaction_id'), table_name='followups')
    op.drop_index(op.f('ix_followups_assigned_to'), table_name='followups')
    op.drop_table('followups')
    # ### end Alembic commands ###
